### ISSUE TITLE
Please mark clearly that this repository is obsolete (or remove it)

### ISSUE THREAD

**Issue by mquinson** [mickours/execo#1]
Salut Mickael,

when wanting to install execo, we came to this repository, but it turns out that it's not updated since 4 years. Could you please do something to not trap the future users of execo in the past?

Thanks, Mt.

**Comment by mickours** [comment]
Salut!

Sorry about that, this is an old fork fixing old issues. Maybe it is still in use in some old tutorials so I'll keep it here.

I've just added a deprecation notice in the readme and I'll now archive this. repo.

Merci Martin :)
